[tool.poetry]
name = "weaselbot"
version = "0.1.0"
description = ""
authors = ["Evan Petzoldt <evan.petzoldt@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
asttokens = "2.2.1"
backcall = "0.2.0"
black = "23.1.0"
click = "8.1.3"
comm = "0.1.2"
debugpy = "1.6.6"
decorator = "5.1.1"
executing = "1.2.0"
greenlet = "2.0.2"
importlib-metadata = "6.0.0"
ipykernel = "6.21.2"
ipython = "8.10.0"
jedi = "0.18.2"
jupyter-client = "8.0.3"
jupyter-core = "5.2.0"
matplotlib-inline = "0.1.6"
mypy-extensions = "1.0.0"
mysql-connector-python = "8.0.32"
nest-asyncio = "1.5.6"
numpy = "1.24.1"
packaging = "23.0"
pandas = "1.5.3"
parso = "0.8.3"
pathspec = "0.11.1"
pexpect = "4.8.0"
pickleshare = "0.7.5"
platformdirs = "3.0.0"
prompt-toolkit = "3.0.37"
protobuf = "3.20.3"
psutil = "5.9.4"
ptyprocess = "0.7.0"
pure-eval = "0.2.2"
pygments = "2.14.0"
pymysql = "1.0.2"
python-dateutil = "2.8.2"
python-dotenv = "0.21.1"
pytz = "2022.7.1"
pyzmq = "25.0.0"
six = "1.16.0"
slack-sdk = "3.19.5"
sqlalchemy = "1.4.16"
stack-data = "0.6.2"
tomli = "2.0.1"
tornado = "6.2"
traitlets = "5.9.0"
typing-extensions = "4.4.0"
wcwidth = "0.2.6"
zipp = "3.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
